### ISSUE TITLE
Windows環境でrst2html.pyを実行出来ない

### ISSUE THREAD

**Issue by kannokanno** [kannokanno/previm#27]
恐らく以下のような原因

* `rst2html.py`には実行権限(+x)が付いていないのではないか
* ので`rst2html.py`単体では動かせず、`python rst2html.py`とする必要がある

**Comment by kannokanno** [comment]
@HappyLuckyAkira
以下を試してみて頂けますでしょうか？

1. `vimrc`の編集
  * NeoBundleでブランチ指定

    ```vimL
    " この部分を変更
    " NeoBundle 'kannokanno/previm'
    NeoBundle 'kannokanno/previm', '27-fix-rst2html-on-windows'
    ```
  * previm用の設定を追加

    ```vimL
    let g:previm_disable_vimproc = 1
    ```
1. `:NeoBundleInstall`する
1. 念のためVimを再起動する
1. 通常通りの操作でreStructuredTextのファイルに対して`:PrevimOpen`を実行する

確認して頂きたいことは以下の点です。

* 正常に実行出来るか
* 実行に失敗した場合はエラー内容
* 成功した場合、DOS窓は表示されてしまうか

**Comment by HappyLuckyAkira** [comment]
ご対応、ありがとうございます。
ちょっと今週来週とバタバタしておりまして、少し確認が遅くなってしまうかもしれません。
しばしお待ちいただけますか？（ちょっと違うことをしていまして）

そして、コメントを拝見すると、もしかしたら、私は使い方を誤っていたのかもと思ったりもします

**Comment by kannokanno** [comment]
承知しました。
全然いつでも大丈夫ですので！

**Comment by HappyLuckyAkira** [comment]
別件で、全然手出しできてません。
大変申し訳ありません

**Comment by kannokanno** [comment]
いえいえー、お気になさらず！

**Comment by HappyLuckyAkira** [comment]
* 正常に実行出来るか
→できます（多分）
ところどころ、
Unknown directive type "toctree".
.. toctree::
   :maxdepth: 2
みたいなのが、表示されますが。

* 成功した場合、DOS窓は表示されてしまうか
→表示されてないように見えます。

**Comment by kannokanno** [comment]
ご確認ありがとうございます。
> Unknown directive type "toctree".

toctreeはsphinxの拡張構文であり、docutilsではそれを解釈出来ないようですね。
sphinx/docutils側の話ですが解決方法は分からず...。

上記ブランチの対応でよければmasterにマージしようと思いますがいかがでしょうか？

**Comment by HappyLuckyAkira** [comment]
マージお願いします！

**Comment by kannokanno** [comment]
masterにmergeしました。
上記対応のこちらは戻して頂いて問題ありません。

```vim
" NeoBundle 'kannokanno/previm'
NeoBundle 'kannokanno/previm', '27-fix-rst2html-on-windows'
```

↓

```vim
NeoBundle 'kannokanno/previm'
```

**Comment by HappyLuckyAkira** [comment]
承知しました！

**Comment by HappyLuckyAkira** [comment]
マージ確認しました。
ついでに、NeoBundleがバージョンアップされて
エラーでまくりでしたけどwww

**Comment by kannokanno** [comment]
確認ありがとうございます :+1:
