### ISSUE TITLE
mermaid.css set opacity of .section in rst file.

### ISSUE THREAD

**Issue by lambdalisue** [kannokanno/previm#43]
![screenshot 2015-12-09 22 59 51](https://cloud.githubusercontent.com/assets/546312/11687232/c231c2c8-9ec8-11e5-9eb6-7e175016e6c0.png)

reStructured automatically create a `div.section` so previm should automatically override that CSS I guess?

**Comment by delijati** [comment]
Same problem. Its unreadable.

**Comment by kannokanno** [comment]
Thanks.
Let me confirm.

**Comment by hartzell** [comment]
I see something similar in a document created by MkDocs.  The copy of mermaid.css from the [MkDocs+ project](http://bwmarrin.github.io/MkDocsPlus/) works.

**Comment by kannokanno** [comment]
Sorry for the delay.
It should have been resolved by #60

**Comment by lambdalisue** [comment]
It has had been fixed but appeared again.

<img width="1089" alt="index html 2018-01-25 13-48-27" src="https://user-images.githubusercontent.com/546312/35371295-a5b581f2-01d6-11e8-97ac-34055260eeab.png">

Confirmed with 5d780c0

**Comment by lambdalisue** [comment]
Prob. https://github.com/kannokanno/previm/commit/d16310e360a40198fc8faf7732cb0545114972cf ?

I think previm should overwrite the CSS instead of directly modifying the library CSS.
