### ISSUE TITLE
:PrevimOpenが起動しない

### ISSUE THREAD

**Issue by lv7777** [kannokanno/previm#45]
> E492: エディタのコマンドではありません: PrevimOpen

というエラーが出てコマンドすら打てません。neobundle以外のプラグインやほぼ全てのVimrcを消してみても変わりませんでした。file type(.md)の設定やprevim_open_cmdを設定しても変わりませんでした。

64-bit,windows10、kaoriya vim版です。

**Comment by Shougo** [comment]
PreVimOpen コマンドは mkd,markdown,rst,textile filetype でしか定義されません。
おそらく、その他の filetype のバッファで実験しているのではないかと思うのですが、どうでしょうか。

**Comment by Shougo** [comment]
コメントを見る限りPreVim が対応している mkd ではなく、md filetype で作業しているという可能性があります。
残念ながら、MarkDown の filetype は統一されてないので、このようなことは起こりやすいですね。

**Comment by lv7777** [comment]
vimrcで設定した所うまくいきました。ありがとうございます。

ですが今度は #27のような問題が出ました。
 let g:previm_open_cmdを絶対パスで指定するとvimproc#get_command_nameでエラーが出たため

WindowsのPathを設定して"firefox"でfirefoxを起動するように設定した所、

> C:\Program Files (x86)\_____MY____INSTALS\vim74-kaoriya-win64\bundle\plagins\previm\autoload/../preview/index.html

というように絶対パス+相対パス指定＆スラッシュとバックスラッシュが混在する形になっていました。
chromeだとブラウザ側が解釈してくれました。

とりあえずchromeでやっていますがvim側で計算してやることは出来ないでしょうか？

**Comment by Shougo** [comment]
> let g:previm_open_cmdを絶対パスで指定するとvimproc#get_command_nameでエラーが出たため

パスをバックスラッシュで指定していませんか？
バックスラッシュには対応していないので、スラッシュにしてください。

**Comment by lv7777** [comment]
windowsはバックスラッシュが標準なのでスラッシュを指定することは出来ません。。。
> E605: 例外が捕捉されませんでした: vimproc#get_command_name: File "C:/Program" is not found.

スラッシュで絶対パス指定をすると上記のようなエラーが出ます

**Comment by Shougo** [comment]
Windows のコマンドがスラッシュを受けつけるかどうかは、その API やコマンドの実装によります。
確かに一部スラッシュが使えないものが存在するのは事実ですが、「スラッシュを指定することができない」訳ではありません。

@kannokanno 

https://github.com/kannokanno/previm/blob/b130f24277e3c6a5afa3984921516b0a83b31d28/autoload/previm.vim#L14

残念ながら、`g:previm_open_cmd` をエスケープしてないですね……。おそらく原因はこれ。
`printf('"%s" "%s", g:previm_open_cmd, a:preview_html_file)` としたほうがよいかな。

**Comment by kannokanno** [comment]
@Shougo さんフォローありがとうございます！

ご迷惑をおかけしますが最近余裕がなく、確認/対応までもう少しお待ちください。

**Comment by Shougo** [comment]
No problem

**Comment by lv7777** [comment]
パッチを送りました。よろしくお願いします。
@kannokanno
