### ISSUE TITLE
error on windows 10

### ISSUE THREAD

**Issue by chantisnake** [kannokanno/previm#50]
Hi I am running on a windows machine, and if I type `:PrevimOpen` it gives me the following error

![capture](https://cloud.githubusercontent.com/assets/10100995/13385141/767ee45e-de6b-11e5-808a-565752356feb.PNG)

Originally I think is some windows temp file management error, I have restarted the machine, but still nothing is working...

I have only set the open_cmd in my .vimrc:
```vim
" set previm cmd
let g:previm_open_cmd = 'start' 
```

**Comment by chantisnake** [comment]
I have installed `open-browser`, and previm works, but there is another issue, previm is not updation in realtime, only when I saved the file...

I have installed `rst2html.py`
<img width="378" alt="capture" src="https://cloud.githubusercontent.com/assets/10100995/13397174/c48d5224-dec6-11e5-9a8e-31bc0c949acf.PNG">
and the script is added to path
<img width="310" alt="screenshot - copy 2" src="https://cloud.githubusercontent.com/assets/10100995/13397205/f4c67c36-dec6-11e5-8af7-6c2b9f7899c7.png">

**Comment by gitterliu** [comment]
This is what I'm using 
```
let g:previm_open_cmd = 'start C:\\Program\ Files\\Mozilla\ Firefox\\firefox.exe'
```
it seems like nothing wrong to me.

**Comment by chantisnake** [comment]
It is working now
