### ISSUE TITLE
dein.vim などで遅滞ロードをした際に PrevimOpen コマンドが見つからない

### ISSUE THREAD

**Issue by lambdalisue** [kannokanno/previm#54]
FAQ などに以下のような対処法を書いておくと良いと思います。

```vim
if dein#tap('previm') " {{{
  function! s:previm_on_post_source() abort
    doautocmd Previm FileType
  endfunction
  augroup dein_autocmd_for_previm
    autocmd! *
    execute printf(
          \ 'autocmd User dein#post_source#%s call %s()',
          \ g:dein#name, 's:previm_on_post_source',
          \)
  augroup END
endif " }}}
```

**Comment by Shougo** [comment]
Hm.  It is dein.vim problem.

This is reproduced in the latest dein.vim?

**Comment by lambdalisue** [comment]
I'm using latest.
Well, this would happen when you use `on_cmd` lazy loading instead of `on_ft` like

```toml
[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
```

While previm define `PrevimOpen` command only in a buffer which filetype is `markdown`, `doautocmd Previm FileType` is required when I use `on_cmd` lazy loading.

**Comment by Shougo** [comment]
Hm...  I cannot reproduce it.  dein.vim checks `autocmd FileType` and resets it.

**Comment by lambdalisue** [comment]
I'm very sorry. It was my fault. I thought I was using a latest version but it wasn't.

I put `dein.vim` into `~/.vim/bundle/repo/dein.vim` but dein.vim install dein.vim itself into `~/.vim/bundle/repo/github.com/Shougo/dein.vim` so `call dein#install()` won't update the correct one. When I update `dein.vim` to the latest, I confirmed that this problem no longer exist.

**Comment by lambdalisue** [comment]
最新版の dein.vim で上記のようなコードを追記しなくても動作することが確認できたため閉じます。お騒がせしました :mask:
