### ISSUE TITLE
Preview command on Windows 10 with Firefox - URL is wrong

### ISSUE THREAD

**Issue by Ian2020** [kannokanno/previm#62]
Great plugin, I've been looking for this for ages. However I get a bad URL when I try to preview. I set my open cmd to:
`let g:previm_open_cmd = 'cmd /c start Firefox'`
...and Firefox is launched but the URL is:
`http://www.'c.com/Users/Ian/vimfiles/bundle/previm/preview/index.html'`
Is there a way to fix this?

**Comment by PandaPony** [comment]
Same here,  did you solve it @Ian2020 ?

**Comment by Ian2020** [comment]
No - I have not looked into it since and I still have the problem.
