### ISSUE TITLE
大きな画像が右にはみ出る

### ISSUE THREAD

**Issue by ikuwow** [kannokanno/previm#65]
imgに対するCSSがないため、横幅の大きな画像を読み込ませたときにはみ出て、プレビューに支障をきたします。

いまは手元だと手動で以下のCSSを書いています。

```
img {
  width: 100%;
}
```

**Comment by Bakudankun** [comment]
デフォルトのCSSも結構古いですし、今のGitHubに近い物（そのままでは使えなさそうですが[sindresorhus/github-markdown-css](https://github.com/sindresorhus/github-markdown-css)あたり？）に差し替えるのも良いと思います。

**Comment by kannokanno** [comment]
ありがとうございます。
11/15(火)は日中PCを開けないので、16日にでも確認しますー。

**Comment by kannokanno** [comment]
ひとまず`img`のcssを追加しました。

**Comment by ikuwow** [comment]
大変今更なのですが`max-width: 100%;` にすべきかと思いました
