### ISSUE TITLE
Nothing happens on :PrevimOpen

### ISSUE THREAD

**Issue by PandaPony** [kannokanno/previm#72]
Hi

Tried  

    let g:previm_open_cmd = 'open -a Firefox'
    let g:previm_open_cmd = 'open -a Chromium'

Any suggestions?

Arch Linux

**Comment by kannokanno** [comment]
Hmm.

Please check this out.

1. `:set filetype` is `markdown` or `mkd`
1. Firefox startup command
    - `open -a Firefox` is a command on Mac
    - Set the command to fire Firefox on the terminal of Arch Linux

**Comment by PandaPony** [comment]
let g:previm_open_cmd = 'chromium'

Works perfect now, thank you so much for your awesome work :100:
