### ISSUE TITLE
Github flavour checkbox

### ISSUE THREAD

**Issue by RidaAyed** [kannokanno/previm#75]
Hi

Does one know how to style checkboxes in github flavour?
## Now
`- [ ] unchecked`
`- [x] checked`
## How?
- [ ] unchecked
- [x] checked

**Comment by letientai299** [comment]
Isn't check box is already supported?

![image](https://user-images.githubusercontent.com/8386780/36932479-73138a14-1f04-11e8-87c1-9dcf02a6fa8d.png)
